Delete when write is called with an empty string

diff --git a/Scull-Modified-For-HW4/buildAndLoad b/Scull-Modified-For-HW4/buildAndLoad
--- a/Scull-Modified-For-HW4/buildAndLoad
+++ b/Scull-Modified-For-HW4/buildAndLoad
@@ -1,4 +1,9 @@
 #!/bin/sh
 make
-sudo ./kv_mod_unload
-sudo ./kv_mod_load
+if [ $? -eq 0 ]
+then
+    sudo ./kv_mod_unload
+    sudo ./kv_mod_load
+else
+    printf "ERROR\n"
+fi
